### ISSUE TITLE
EPIC: Crosschain 

### ISSUE THREAD

**Issue by steffenkux** [corpus-io/dm3#666]
## Current behavior

The messenger must be connected to the Ethereum mainnet. DM§ Profiles can be published only to ENS natively. Profiles on other chains are supported (read-only) if they are linked to ENS Subdomains via CCIP.

## Requirements

The messenger must be connected to Ethereum Mainnet for reading (from ENS and linked ENS-Subdomains). The user can log in with any other supported chain (e.g. Gnosis). Publishing the profile is done according to the connected chain (Ethereum -> ENS, Gnosis -> Genome (SpaceID), BSC -> SpaceID, ...). Reading is done on ENS -> subdomains linked with CCIP. A Toplevel-Alias-Link table defines the aliases for read (e.g. gno -> gnosis.eth).
Every chain connected to the **dm3 ecosystem** must be linked to an ENS subdomain linked in the top-level alias list.

## Tasks

- [ ] Include internal web3 connection to read from ENS
- [ ] Add a generalized interface to write to local name services according to the connected chain
- [ ] Toplevel-Alias: Develop smart contract
